### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JayTam** [dooboolab/flutter_sound#342]
## Flutter Sound Version : 

- **Released** or **Beta** version ?
Released
- Version number ?
4.0.0
- **FULL** or **LITE** flavor ?
FULL
----------------------------------------------------------

## Severity

- Result is not what expected ?

--------------------------------------------------------

## Platforms you faced the error 

- iOS 13.4.1

I only test by iOS real device

- Real device 

----------------------------------------------

## flutter pub deps :
```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_blue: 0.7.2
  flutter_sound: ^4.0.0
  gradient_app_bar: ^0.1.3
  dio: 3.0.9
  uuid: 2.0.4
  rxdart: 0.24.0
  provider: 4.0.4
  sqflite: 1.3.0
  fluttertoast: ^4.0.0
  pull_to_refresh: ^1.5.7
  flutter_incall_manager:
    git:
      url: https://github.com/JayTam/flutter-incall-manager

```
------------------------------------------------

##  Screenshots

![image](https://user-images.githubusercontent.com/31993846/81202611-71608100-8ff9-11ea-8f06-c24cce450295.png)

![image](https://user-images.githubusercontent.com/31993846/81202734-96ed8a80-8ff9-11ea-8d27-76113238d07f.png)

-----------------------------------------------------

**Describe the bug**

I connect a bluetooth headset named `TOFO`, but I still wanna record use `iPhone`.
I enter iOS Audio Manager to change audio device from `TOFO` to `iPhone` in the picture above, then I call `recorderModule.startRecorder()` to record, it still record by `TOFO`, is these a bug ?

**To Reproduce**

1. use iPhone connect a `bluetooth headset`
2. enter iOS Audio Manager to change audio device from `bluetooth headset` to `iPhone`
3. use flutter_sound to record
4. it still record by `bluetooth headset`

**Expected behavior**

- When iOS have chosen an audio device, flutter_sound should use the chosen audio device to record or play.
- Or provide a parameter to `recorderModule.startRecorder()` to specify which audio device to record. 

-----------------------------------------------------------------
