### ISSUE TITLE
[HELP] Build fail when used along with firebase_database

### ISSUE THREAD

**Issue by tle-huu** [dooboolab/flutter_sound#448]
## Flutter Sound Version : 

5.1.1 & 4.0.0

- Result of the command **"flutter pub deps | grep flutter_sound"** : 

|-- flutter_sound 5.1.1

----------------------------------------------------------

## Severity

- Cannot build my App

--------------------------------------------------------

## Platforms you faced the error 

Android

Emulator

## flutter doctor

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.3 at /Users/terencelehuuphuong/projects/flutter_test/flutter
    • Framework revision 216dee60c0 (5 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/terencelehuuphuong/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```

----------------------------------------------

## Logs
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.cursoradapter:cursoradapter' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Running Gradle task 'assembleAarRelease'...
Building plugin firebase_core...
Exception: The plugin firebase_core could not be built due to the issue above.
```

------------------------------------------------

**Description of  the bug**

When pubspec.yaml contains flutter_sound AND **firebase_database**, the build crashes.

Here is the pubspec.yaml file:

```
name: flutter_sound_test
description: A new Flutter application.

/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_sound: ^5.1.1
  firebase_database: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


```

**To Reproduce**
1. Make a simple main:

```

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    //BUILD MAIN LAYOUT
    return MaterialApp(title: 'Fill the beat', home: Text("Ewqewq"));
    // return MaterialApp(title: 'Fill the beat', home: ChooseCoverImage());
  }
}

```

2. Add these two lines in the pubspec.yaml file:

```
  flutter_sound: ^5.1.1
  firebase_database: ^3.1.0
```
3. Try to build

**Expected behavior**

Successful build.
